### ISSUE TITLE
Avoid storage of entity FQCN

### ISSUE THREAD

**Issue by yann-eugone** [prestaconcept/PrestaSonataSavedFiltersBundle#7]
Currently, we are storing `admin class` associated with `SavedFilters` entity.
We need such information to be able to find out for which admin the filter was saved for.
But storing an FQCN in a database has drawbacks :
- it is a "sensitive" information
- you are exposing unecessary technical information
- you will have to migrate data whenever you rename the entity

I suggest to store the sonata admin code instead.
It will create a BC, because many things will change, and the existing filers won't be working anymore.

**Comment by J-Ben87** [comment]
At first it would seem like a good idea, but with deeper look maybe not so much: IMHO the 3 points remain valid with the admin code:
- is it really a less sensitive information than an entity's FQCN?
- it's also a technical information
- you would also need a migration whenever you would change your admin's code (or class name if the code is based on the admin's FQCN)

Therefore I'm not sure it would bring any major improvements.
What do you think?

**Comment by yann-eugone** [comment]
Yeah, for the moment, I think you are right, I do not see that much benefit switching
It was FTR anyway, thanks :)
